cloud:
  aws:
    credentials:
        access-key: AKIARNAUGO7BQLIKZVAK
        secret-key: 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

# TODO: Alternatives to root user access keys is create an IAM user with an access key and apply least privilege permissions for that user
# TODO: Create a .env file to store keys.



#    access-key: process.env.AWS_Access_Key_ID
#    secret-key: AWS_Secret_Access_Key

    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: directorytz


#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 5MB
#      max-request-size: 10MB

server:
  port: 8080

